services:
  opencode-web:
    build: .
    command: ["opencode", "web", "--hostname", "0.0.0.0", "--port", "4096"]
    environment:
      - OPENCODE_SERVER_PASSWORD=Qw2e3r4
    network_mode: host
    volumes:
      - ../:/workspace
      - ~/.local/share/opencode:/root/.local/share/opencode
      - ~/.local/state/opencode:/root/.local/state/opencode
      - /var/run/docker.sock:/var/run/docker.sock

  opencode-telegram:
    build: .
    command: ["opencode-telegram", "start"]
    environment:
      - OPENCODE_API_URL=http://0.0.0.0:4096
      - OPENCODE_SERVER_PASSWORD=Qw2e3r4
    depends_on:
      - opencode-web
    profiles: [telegram]
    network_mode: host
    volumes:
      - ~/.config/opencode:/root/.config/opencode
      - ~/.config/opencode-telegram-bot:/root/.config/opencode-telegram-bot
